# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_population as pp
import gis

Import('*')

pop_tif = '/Users/ztessler/data/GPWv4_beta/gpw-v4-population-density-adjusted-to-2015-unwpp-country-totals-{0}/gpw-v4-population-density-adjusted-to-2015-unwpp-country-totals_{0}.tif'

for year in years:
    env.Command(
            source=['#data/Global/deltas.json',
                    pop_tif.format(year)],
            target='#data/Global/delta_pop_dens_{}.pd'.format(year),
            action=gis.delta_zonal_stats)

    env.Command(
            source=['#data/Global/basins.tif',
                    pop_tif.format(year)],
            target='#data/Global/pop_dens_{}.tif'.format(year),
            action=gis.regrid_to_raster,
            method='average')

    for delta in deltas:
        env.Command(
                source=['#data/{0}/{0}.json'.format(delta),
                        pop_tif.format(year)],
                target='#data/{0}/{0}_pop_{1}.tif'.format(delta, year),
                action=pp.clip_pop_to_delta)

        env.Command(
                source=['#data/{0}/{0}.json'.format(delta),
                        '#data/{0}/{0}_srtm{1}.tif'.format(delta, srtm_resolution),
                        '#data/{0}/{0}_pop_{1}.tif'.format(delta, year)],
                target='#data/{0}/{0}_pop_by_srtm{1}_elevations_{2}.pd'.format(delta, srtm_resolution, year),
                action=pp.pop_elevation_bins,
                delta=delta)

        env.Command(
                source='#data/{0}/{0}_pop_by_srtm{1}_elevations_{2}.pd'.format(delta, srtm_resolution, year),
                target='#plots/{0}/{0}_hypsometric_srtm{1}_{2}.png'.format(delta, srtm_resolution, year),
                action=pp.plot_hypsometric,
                delta=delta)

