# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_subsidence as ps

Import('*')

env.Command(
        source=['#data/Global/delta_areas.pd',
                experiments['pristine']['Qs']],
        target='#data/Global/natural_subsidence.pd',
        action=ps.steady_state_subsidence,
        eustatic_slr=experiments['pristine']['eustatic_slr'])

env.Command(
        source='/Users/ztessler/data/Groundwater_Wada2012/gwd02000.asc',
        target='#data/Global/groundwater.tif',
        action='gdal_translate -of GTiff $SOURCE $TARGET')
