# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_risk as pr
from itertools import combinations

Import('*')

for experiment, config in experiments.iteritems():

    if config['vuln_source'][0] == 'tessler2015':
        env.Command(
                source=[config['vuln_source'][1],
                        config['delta_zeros']],
                target=config['vuln'],
                action=pr.import_idi_vuln)

    env.Command(
            source=[config['surge_annual_exposure'],
                    config['vuln']],
            target=config['surge_risk'],
            action=pr.adj_annual_exposure_for_vuln)

    env.Command(
            source=[config['surge_risk'],
                    config['pop_hypso_growth']],
            target=config['surge_percap_risk'],
            action=pr.per_capita_exposure)

    for delta in common['deltas']:
        env.Command(
                source=config['surge_annual_exposure'],
                target=config['surge_annual_exposure_plot'].format(delta=delta, ext='png'),
                action=pr.plot_surge_annual_exposure,
                delta=delta,
                exp=config['name'])

for (expA, expB) in combinations(experiments.keys(), 2):
    for delta in common['deltas']:
        scenarios = expA + '_' + expB
        env.Command(
                source=[experiments[expA]['surge_annual_exposure'],
                        experiments[expB]['surge_annual_exposure']],
                target=config['surge_annual_exposure_comparison_plot'].format(delta=delta, scenarios=scenarios, ext='png'),
                action=pr.plot_surge_annual_exposure_multiscenario,
                delta=delta,
                names=[experiments[expA]['name'], experiments[expB]['name']])
