# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_risk as pr
from itertools import combinations

Import('*')

for experiment, config in experiments.iteritems():

    env.Command(
            source=[config['surge_annual_exposure'],
                    config['vuln']],
            target=config['surge_risk'],
            action=pr.adj_annual_exposure_for_vuln)

    env.Command(
            source=[config['surge_risk'],
                    config['pop_hypso_growth']],
            target=config['surge_percap_risk'],
            action=pr.per_capita_exposure)

    myCommand(
            source=[config['hazards_index'],
                    config['rslr'],
                    config['total_vuln']],
            target=config['risk_quadrants_plot_snapshot'],
            action=[pr.plot_risk_quadrants,
                    'convert -trim $TARGET $TARGET'],
            hazard_name='Hazard Index',
            exposure_name='RSLR, mm/y',
            vuln_name='Socio-economic Capacity',
            RCP='none',
            hazard_window='historical',
            SSP='SSP2',
            forecast=2010,
            delta_labels=['Mississippi', 'Nile', 'Ganges', 'Amazon', 'Pearl'],
            )

    for delta in common['deltas']:
        myCommand(
                source=config['surge_annual_exposure'],
                target=config['surge_annual_exposure_plot'].format(delta=delta, ext='png'),
                action=[pr.plot_surge_annual_exposure,
                        'convert -trim $TARGET $TARGET'],
                delta=delta,
                exp=config['name'])

scenarios, configs = zip(*list(experiments.iteritems()))
env.Command(
        source=[c['surge_annual_exposure'] for c in configs],
        target=config['surge_annual_exposure_ranges'],
        action=pr.compute_exposure_ranges)

# for (expA, expB) in combinations(experiments.keys(), 2):
for expA in experiments.keys():
    for expB in experiments[expA]['compare_with']:
        scenarios = expA + '_' + expB
        myCommand(
                source=[experiments[expA]['surge_annual_exposure'],
                        experiments[expB]['surge_annual_exposure'],
                        config['surge_annual_exposure_ranges']],
                target=config['surge_annual_exposure_comparison_multidelta_plot'].format(scenarios=scenarios, ext='png'),
                action=[pr.plot_surge_annual_exposure_multiscenario_multidelta,
                        'convert -trim $TARGET $TARGET'],
                scenarios=[experiments[expA]['name'], experiments[expB]['name']])
        for delta in common['deltas']:
            myCommand(
                    source=[experiments[expA]['surge_annual_exposure'],
                            experiments[expB]['surge_annual_exposure']],
                    target=config['surge_annual_exposure_comparison_plot'].format(delta=delta, scenarios=scenarios, ext='png'),
                    action=[pr.plot_surge_annual_exposure_multiscenario,
                            'convert -trim $TARGET $TARGET'],
                    delta=delta,
                    scenarios=[experiments[expA]['name'], experiments[expB]['name']])
