# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_sediment as ps

Import('*')

# convert rgis files to netCDF, use BQART model to estimate sed flux under
# different anthro conditions (including none), use to estimate natural
# subsidence rates based on sed flux, sediment retention ratio (see Syvitski and
# Saito 2007 for ratios) and delta surface area

env.Command(
        source='#data/Global/upstream_ice_percent.pd',
        target='#data/Global/bqart_I.pd',
        action=ps.compute_I)

env.Command(
        source=['#data/Global/reservoir.tif',
                '#data/Global/discharge.tif',
                '#data/Global/basins.tif',
                '#data/Global/upstream_basin_ids.json'],
        target='#data/Global/upstream_trapping_eff.pd',
        action=ps.res_trapping)

env.Command(
        source=['#data/Global/upstream_per_capita_gdp.pd',
                '#data/Global/upstream_pop_dens_2000.pd'], # .format(year)
        target='#data/Global/bqart_Eh.pd',
        action=ps.compute_Eh)
