# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_upstream as pu

Import('*')

env.Command(
        source=['#data/Global/basins.tif',
                '#data/Global/upstream_basin_ids.json',
                '#data/Global/06min_pixel_areas.tif'],
        target='#data/Global/upstream_areas.pd',
        action=pu.agg_over_basins,
        method='sum')

env.Command(
        source=['#data/Global/basins.tif',
                '#data/Global/upstream_basin_ids.json',
                '#data/Global/airtemp.tif',
                '#data/Global/06min_pixel_areas.tif'],
        target='#data/Global/upstream_temps.pd',
        action=pu.agg_over_basins,
        method='weightedmean')

env.Command(
        source=['#data/Global/basins.tif',
                '#data/Global/upstream_basin_ids.json',
                '#data/Global/elevation.tif'],
        target='#data/Global/upstream_relief.1.pd',
        action=pu.agg_over_basins,
        method='max')

env.Command(
        source='#data/Global/upstream_relief.1.pd',
        target='#data/Global/upstream_relief.2.pd',
        action=pu.convert_m_to_km)

env.Command(
        source='#data/Global/upstream_relief.2.pd',
        target='#data/Global/upstream_relief.pd',
        action=pu.clip_neg_to_zero)

env.Command(
        source=['#data/Global/discharge.tif',
                '#data/Global/basin_mouths.pd'],
        target='#data/Global/upstream_discharge.pd',
        action=pu.discharge_at_mouths)
