# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_upstream as pu

Import('*')

env.Command(
        source=['#data/Global/basins.tif',
                '#data/Global/06min_pixel_areas.tif',
                '#data/Global/upstream_basin_ids.json'],
        target='#data/Global/upstream_areas.pd',
        action=pu.agg_over_basins,
        method='sum')
