# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_srtm as ps

Import('*')

for delta in deltas:
    env.Command(
            source='#data/deltas_shp/deltas.shp',
            target='#data/{0}/{0}_srtm{1}_full.tif'.format(delta, srtm_resolution),
            action=ps.delta_srtm_composite,
            delta=delta,
            resolution=srtm_resolution)

    env.Command(
            source=['#data/deltas_shp/deltas.shp',
                    '#data/{0}/{0}_srtm{1}_full.tif'.format(delta, srtm_resolution)],
            target='#data/{0}/{0}_srtm{1}.tif'.format(delta, srtm_resolution),
            action=ps.clip_srtm_to_delta,
            delta=delta,
            resolution=srtm_resolution)


