# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_srtm as ps

Import('*')

for experiment, config in experiments.iteritems():
    elevs = []
    lengths = []
    for delta in common['deltas']:
        env.Command(
                source=config['delta_map'].format(delta=delta),
                target=config['delta_srtm_full_rast'].format(
                            delta=delta, srtm=config['srtm']),
                action=ps.delta_srtm_composite,
                delta=delta,
                resolution=config['srtm'])

        env.Command(
                source=[config['delta_map'].format(delta=delta),
                        config['delta_srtm_full_rast'].format(
                            delta=delta, srtm=config['srtm'])],
                target=config['delta_srtm_rast'].format(
                            delta=delta, srtm=config['srtm']),
                action=ps.clip_srtm_to_delta)

        env.Command(
                source=config['delta_srtm_rast'].format(delta=delta, srtm=config['srtm']),
                target=config['delta_max_elev'].format(delta=delta),
                action=ps.estimate_max_elev,
                percentile=config['delta_max_elev_percentile'])
        elevs.append(config['delta_max_elev'].format(delta=delta))

        env.Command(
                source=config['delta_map'].format(delta=delta),
                target=config['delta_length'].format(delta=delta),
                action=ps.estimate_delta_length)
        lengths.append(config['delta_length'].format(delta=delta))

    env.Command(
            source=elevs,
            target=config['deltas_max_elev'],
            action=ps.txt_nums_to_df,
            deltas=common['deltas'])

    env.Command(
            source=lengths,
            target=config['deltas_length'],
            action=ps.txt_nums_to_df,
            deltas=common['deltas'])

    env.Command(
            source=[config['deltas_max_elev'],
                    config['deltas_length']],
            target=config['delta_gradients'],
            action=ps.compute_gradient,
            geo_scaling=4) # extra length of river due to meandering, and delta shape deviations from a circle
