# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_srtm as ps

Import('*')

for experiment, config in experiments.iteritems():
    for delta in deltas:
        env.Command(
                source=config['delta_map'].format(delta=delta),
                target=config['delta_srtm_full_rast'].format(
                            delta=delta, srtm=config['srtm']),
                action=ps.delta_srtm_composite,
                delta=delta,
                resolution=config['srtm'])

        env.Command(
                source=[config['delta_map'].format(delta=delta),
                        config['delta_srtm_full_rast'].format(
                            delta=delta, srtm=config['srtm'])],
                target=config['delta_srtm_rast'].format(
                            delta=delta, srtm=config['srtm']),
                action=ps.clip_srtm_to_delta)
