# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import process_analysis as pa

Import('*')

myCommand(
        source=[experiments['contemp']['rslr'],
                experiments['zarfl-reservoirs']['rslr'],
                experiments['US-reservoir-utilization']['rslr'],
                experiments['retention-low']['rslr'],
                experiments['USresutil-and-retentionlow']['rslr'],
                experiments['pristine']['natural_subsidence'],
                experiments['pristine']['Qs'],
                experiments['contemp']['Qs'],
                experiments['zarfl-reservoirs']['Qs'],
                experiments['US-reservoir-utilization']['Qs'],
                experiments['contemp']['delta_areas'],
                ],
        target=experiments['contemp']['analysis'],
        action=pa.analysis)

myCommand(
        source=experiments['contemp']['basin_mouths'],
        target=experiments['contemp']['deltas_map'],
        action=[pa.plot_global_map,
                'convert -trim $TARGET $TARGET'],
        drop=['Congo', 'Tone'])
