# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import process_analysis as pa

Import('*')

myCommand(
        source=[experiments['contemp']['rslr'],
                experiments['zarfl-reservoirs']['rslr'],
                experiments['US-reservoir-utilization']['rslr'],
                experiments['retention-low']['rslr'],
                experiments['USresutil-and-retentionlow']['rslr'],
                experiments['pristine']['natural_subsidence'],
                experiments['pristine']['Qs'],
                experiments['contemp']['Qs'],
                experiments['zarfl-reservoirs']['Qs'],
                experiments['US-reservoir-utilization']['Qs'],
                experiments['contemp']['delta_areas'],
                ],
        target=experiments['contemp']['analysis'],
        action=pa.analysis)

myCommand(
        source=experiments['contemp']['basin_mouths'],
        target=experiments['contemp']['deltas_map'],
        action=[pa.plot_global_map,
                'convert -trim $TARGET $TARGET'],
        drop=['Congo', 'Tone'])

myCommand(
        source=[experiments['contemp']['rslr'],
                experiments['US-reservoir-utilization']['rslr'],
                experiments['retention-low']['rslr']],
        target=experiments['contemp']['rslr_dist_plot'],
        action=[pa.rslr_distribution_plot,
                'convert -trim +repage -bordercolor white -border 2 $TARGET $TARGET'],
        names=[experiments['contemp']['name'],
               experiments['US-reservoir-utilization']['name'],
               experiments['retention-low']['name']],
        drop=['Congo', 'Tone'])

myCommand(
        source=[experiments['contemp']['natural_subsidence'],
                experiments['pristine']['Qs'],
                experiments['contemp']['Qs'],
                experiments['contemp']['rslr'],
                experiments['US-reservoir-utilization']['rslr'],
                experiments['retention-low']['rslr'],
                experiments['USresutil-and-retentionlow']['rslr'],
            ],
        target=experiments['contemp']['data_table_for_paper'],
        action=pa.delta_data_to_csv,
        columns=['Natural Subsidence (mm/year)',
                 'Sediment Flux, Pristine (kg/s)',
                 'Sediment Flux, Contemporary (kg/s)',
                 'Relative Sea-Level Rise Rate, Contemporary (mm/year)',
                 'Relative Sea-Level Rise Rate, Reservoir Growth (mm/year)',
                 'Relative Sea-Level Rise Rate, Low Sediment Retention (mm/year)',
                 'Relative Sea-Level Rise Rate, Reservoir Growth and Low Sediment Retention (mm/year)',
            ])

myCommand(
        source=None,
        target=[experiments['contemp']['cartoon_rslr'],
                experiments['contemp']['cartoon_resilience1'],
                experiments['contemp']['cartoon_resilience2'],
                experiments['contemp']['cartoon_floods']],
        action=pa.plot_resilience_cartoons)
