# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_delta_geog as geo

Import('*')

# Import delta shapefile and regroup from polygons to multipolygons by delta
env.Command(
        target='#data/Global/deltas.json',
        source='/Users/ztessler/data/deltas/global_map_shp/global_map.shp',
        action=geo.group_delta_shps,
        )

for delta in deltas:
    env.Command(
            target='#data/{0}/{0}.json'.format(delta),
            source='#data/Global/deltas.json',
            action=geo.delta_geojson,
            delta=delta)

env.Command(
        source=['#data/Global/deltas.json',
                '#data/Global/basins.tif'],
        target='#data/Global/upstream_basin_ids.json',
        action=geo.contributing_basins)

env.Command(
        source=['#data/Global/basins.pd',
                '#data/Global/discharge.tif',
                '#data/Global/upstream_basin_ids.json'],
        target='#data/Global/basin_mouths.pd',
        action=geo.locate_basin_mouths)

env.Command(
        source='#data/Global/basins.tif',
        target='#data/Global/06min_pixel_areas.tif',
        action=geo.raster_pixel_areas)
