# vim: set fileencoding=UTF-8 :
# vim:filetype=python

import os
import process_hazards as ph
import gis

Import('*')

for experiment, config in experiments.iteritems():
    if config['storm_surge_source'][0] == 'unisdr':
        env.Command(
                target=config['storm_surge_zip'],
                source=None,
                action='wget "' + config['storm_surge_source'][1] + '" -O $TARGET')

        env.Command(
                target=[config['storm_surge_vect'].replace('.shp', ext) for ext in ['.shp', '.shx',
                                                                                    '.cpg', '.dbf',
                                                                                    '.prj', '.qpj']],
                source=config['storm_surge_zip'],
                action=['unzip $SOURCE -d $$(dirname $TARGET)',
                        'DIRPATH=$$(dirname $TARGET); NAME=$$(basename $${DIRPATH}); for i in $${DIRPATH}/*; do mv "$$i" "$${DIRPATH}/$$NAME.$${i##*.}"; done'])

        env.Command(
                target=config['storm_surge'],
                source=[config['deltas'],
                        config['storm_surge_vect']],
                action=ph.storm_surge_agg_points)

    env.Command(
            target=config['surge_populations'],
            source=[config['storm_surge'],
                    config['pop_hypso_growth_rslr']],
            action=ph.storm_surge_populations)

    env.Command(
            source=config['surge_populations'],
            target=config['surge_annual_exposure'],
            action=ph.surge_expected_expo)

    if config['dis_future_source'][0] == 'isimip':
        rcpdata = []
        years = range(config['dis_future_years'][0], config['dis_future_years'][1]+1)
        for rcp in config['dis_future_rcps']:
            annual_dis = []
            for year in years:
                remotefile = config['dis_future_source'][1].format(gcm=config['dis_future_gcm'], rcp=rcp, year=year, ext='gdbc.gz')
                localtmp = env.File(config['dis_future_tmp'].format(gcm=config['dis_future_gcm'], rcp=rcp, year=year, ext='{ext}')).abspath
                localnc = config['dis_future_ncs'].format(gcm=config['dis_future_gcm'], rcp=rcp, year=year)

                gdbcgz = config['dis_future_tmp'].format(gcm=config['dis_future_gcm'], rcp=rcp, year=year, ext='gdbc.gz')
                gdbc = env.File(config['dis_future_tmp'].format(gcm=config['dis_future_gcm'], rcp=rcp, year=year, ext='gdbc')).abspath
                tmpnc = env.File(config['dis_future_tmp'].format(gcm=config['dis_future_gcm'], rcp=rcp, year=year, ext='nc')).abspath
                env.Command(
                        source=None,
                        target=gdbcgz,
                        action='scp ' + remotefile + ' $TARGET')
                env.Command(
                        source=gdbcgz,
                        target=localnc,
                        action=['gunzip -k $SOURCE',
                                'rgis2netcdf {} {}'.format(gdbc, tmpnc),
                                'nccopy -d1 -s {} $TARGET'.format(tmpnc),
                                'rm {} {}'.format(gdbc, tmpnc)])

                env.Command(
                        source=[config['basin30_mouths'],
                                localnc],
                        target=config['dis_future_annual'].format(year=year, rcp=rcp),
                        action=ph.extract_future_delta_discharge,
                        year=year)

                annual_dis.append(config['dis_future_annual'].format(year=year, rcp=rcp))

            env.Command(
                    source=annual_dis,
                    target=config['dis_future_rcp'].format(rcp=rcp),
                    action=ph.combine_future_dis_years,
                    years=years)
            rcpdata.append(config['dis_future_rcp'].format(rcp=rcp))

        env.Command(
                source=rcpdata,
                target=config['dis_future'],
                action=ph.combine_future_dis_rcps,
                rcpnames=config['dis_future_rcps'],
                )

    env.Command(
            source=config['dis_future'],
            target=config['dis_future_extremes_basins'],
            action=ph.model_extremes,
            percentile=99,
            return_period=30,
            window=30)
    env.Command(
            source=config['dis_future_extremes_basins'],
            target=config['dis_future_extremes'],
            action=ph.agg_delta_extremes)

    if config['waves_future_source'][0] == 'csiro':
        gcm_files = []
        for gcm in config['waves_future_gcms']:
            forecast_files = []
            for forecast in config['waves_future_forecasts']:
                rcp_files = []
                for i, rcp in enumerate(config['waves_future_rcps']):
                    monthlyfiles = []
                    if forecast == 'HISTORICAL':
                        # import ipdb;ipdb.set_trace()
                        print 'hhh', gcm, forecast, rcp, i, rcp_files
                        if i>0: # HISTORICAL has no RCPs, so only run once
                            continue
                        rcp = ''

                    # run this step directly, otherwise wont have list of files to create targets from
                    # supposedly ways to make this work through scons (dynamic builds) but isn't working
                    yyyymm_list = config['waves_future_nclist'].format(gcm=gcm, forecast=forecast, rcp=rcp)
                    if not os.path.exists(env.File(yyyymm_list).abspath):
                        env = {'urlformat':config['waves_future_source'][1].format(gcm=gcm, forecast=forecast, rcp=rcp, yyyymm='')}
                        ph.get_waves_nclist(
                                env=env,
                                source=None,
                                target=[yyyymm_list])
                    with open(env.File(yyyymm_list).abspath, 'r') as datelist:
                        for yyyymm in datelist.readlines():
                            yyyymm = yyyymm.strip()
                            monthlydata=config['waves_future_monthly'].format(gcm=gcm, forecast=forecast, rcp=rcp, yyyymm=yyyymm),
                            env.Command(
                                    source=config['waves_future_delta_indices'],
                                    target=monthlydata,
                                    action=ph.process_wave_month,
                                    url=config['waves_future_source'][1].format(gcm=gcm, forecast=forecast, rcp=rcp, yyyymm=yyyymm))
                            monthlyfiles.append(monthlydata)

                    rcp_data = config['waves_future_rcp_data'].format(gcm=gcm, forecast=forecast, rcp=rcp)
                    env.Command(
                            source=monthlyfiles,
                            target=rcp_data,
                            action=ph.concat_waves_times,
                            )

                    historical = config['waves_future_rcp_data'].format(gcm=gcm, forecast='HISTORICAL', rcp='')
                    rcp_zscore = config['waves_future_rcp_zscores'].format(gcm=gcm, forecast=forecast, rcp=rcp)
                    if forecast == 'HISTORICAL':
                        print rcp_files
                    env.Command(
                            source=[historical,
                                    rcp_data],
                            target=rcp_zscore,
                            action=ph.compute_waves_extremes,
                            percentile=99,
                            return_period=30)
                    rcp_files.append(rcp_zscore)

                # forecast_file = config['waves_future_forecast_data'].format(gcm=gcm, forecast=forecast)
                # if forecast == 'HISTORICAL':
                    # rcp_names = ['N/A']
                # else:
                    # rcp_names = config['waves_future_rcps']
                # env.Command(
                        # source=rcp_files,
                        # target=forecast_file,
                        # action=ph.agg_wave_ts_data,
                        # level='RCP',
                        # names=rcp_names)
                # forecast_files.append(forecast_file)

            # gcm_file = config['waves_future_gcm_data'].format(gcm=gcm)
            # env.Command(
                    # source=forecast_files,
                    # target=gcm_file,
                    # action=ph.agg_wave_ts_data,
                    # level='Window',
                    # names=config['waves_future_forecasts'])
            # gcm_files.append(gcm_file)

        # env.Command(
                # source=gcm_files,
                # target=config['waves_future_full_data'],
                # action=ph.agg_wave_ts_data,
                # level='GCM',
                # names=config['waves_future_gcms'])

        # env.Command(
                # source=config['waves_future_full_data'],
                # target=config['waves_future_extremes'],
                # action=ph.compute_waves_extremes)


        # assumes same delta grid indices for each gmc/forecast/rcp nc file
        # just use last gcm/forecast/rcp
        # requires list of ncfiles, downloaded above
        env.Command(
                source=config['deltas'],
                target=config['waves_future_delta_indices'],
                action=ph.waves_find_delta_indices,
                url=config['waves_future_source'][1].format(gcm=gcm, forecast=forecast, rcp=rcp, yyyymm=yyyymm),
                nullval=-999.0)


